@isTest
public class BlockBusterCreditCardTransactTest {
    public static testMethod void BlockBusterCreditCardTransactTest(){

       BlockBusterCreditCardTransact ap=new BlockBusterCreditCardTransact();
       BlockBusterCreditCardTransact apc=new BlockBusterCreditCardTransact('errCd','errMsg');
        ap.customernumber='';
        ap.orderid='';
        ap.createtime='';
        ap.createtime='';
        ap.type='';
        ap.title='';
        ap.product_id='';
        ap.totalprice='';
        ap.koda='';
    }

}