public with sharing class BlockBusterRefund {

	
/*	public static void RefundForKlippKort(String fakturaid){
		
	}
	
	public static void RefundForNonKlippkort(String Fakturaid){
		List<Payment_Invoice__c>lstPayInv = new List<Payment_Invoice__c>([SELECT Account__c,Amount_Applied__c,Amount__c,Applied_Against__c,Aria_Account__c,Aria_Account__r.Aria_Account_No__c,Balance__c,checkPaymentApplied__c,CommentsLong__c,Comments__c,CreatedById,CreatedDate,Credit_Reason__c,Datoforudskrift__c,External_Name__c,Fakturanummer__c,Faktura__c,Id,IsDeleted,isVoid__c,LastModifiedById,LastModifiedDate,Momspligtigt_bel_b__c,Name,Payment_date_time__c,Payment_Date__c,Payment_Type__c,Payment__c,SystemModstamp,Transaction_No__c,transaction_source_id__c,Void_Date__c FROM Payment_Invoice__c where Faktura__c = 'a2bM0000000llFO' and Amount_Applied__c >0]);
		//if(!lstPayInv.isEmpty())
			//BlockBusterCallOut.IssueRefund(lstPayInv[0].Aria_Account__r.Aria_Account_No__c,lstPayInv[0].Transaction_No__c);
	}*/
}