public class CarrieGlobalConstants {
	public static final String toDateGtFromDate = 'Til dato skal være større end Fra dato'; 
	public static final String datesGtToday = 'Fremtidig dato er valgt for til og fra dato feltet';
	public static final String toDateGtToday = 'Til datoen ligger frem i tid.'; 
	public static final String fromDateGtToday = 'Dato for fra dato er en fremtidig dato.';
	public static final String invalidDateFormat = 'Du kan indtaste datoen med følgende: dd-mm-åååå';
	public static final String timeoutError = 'Fejl ved fremsøgning af data fra bagvedliggende systemer. ';
	public static final String noCustNum = 'Kunden blev ikke fundet';
	public static final String jsonParsingError = 'Fejl er opstået ved hentning af data';
	public static final String amount = 'Indtast det beløb som ønskes krediteret';
	public static final String creditReason = 'Indtast årsag for krediteringen';
	public static final String comments = 'Indtast Bemærkning for krediteringen'; 
	public void samplemethod()
	{
	}
}