public class DealerSalesConstant {
    
    public static String pagePrefix = '/apex/';
    //CLEAR PRODUCTS
    public static String clearPageRef = 'clearId';
    public static String clearKravet = 'clearKravet';
    // DW-861
    public static String dtvtaId = 'dtvtaId';
    public static String broadbandPageRef = 'BroadBandProductPage1';
        //Added for DW-851
    public static String securitypakkenPageRef= 'securitypakkenProductsPage1';
    public static String telifoniPageRef= 'telefoniProductsPage1';
    public static String plusPageRef = 'DtvHardwareSelection';
    public static String extraPageRef = 'FreeChoice';
    public static String clearId = 'clearId';
    public static String broadbandId = 'broadbandId';
    //Added for DW-851
    public static String securitypakkenId = 'securitypakkenId';
    public static String telephonyId = 'telephonyId';   
    public static String bbModemId = 'bbModemId';
    public static String bbTlfCommonId ='bbTlfCommonId'; 
    public static String bbSPCommonId ='bbSPCommonId'; 
    public static String SPTlfCommonId ='SPTlfCommonId'; 
    public static String bbSPTlfCommonId ='bbSPTlfCommonId'; 
    public static String BroadBandModemId = 'BroadBandModemId'; 
    public static String TelephoniProductId = 'TelephoniProductId';  
    public static String SPProductId = 'SPProductId';    
    public static String NEW_CUSTOMER = 'Ny Kunde';
    //DTV & FC
    public static String dtvEngId = 'dtvEngId';//HARDWARE SELECTION FOR dtv
    public static String dtvPakkeId = 'dtvPakkeId';//HARDWARE SELECTION FOR FC
    public static String dtvSerialNoEntry = 'dtvSerialNoEntry';
    public static String fcSerialNoEntry = 'fcSerialNoEntry';
    
    public static String dtvCardSelectId = 'dtvCardSelectId';
    public static String fcCardSelectId = 'fcCardSelectId';
    
    public static String dtvChannelSelId = 'dtvChannelSelId';
    public static String fcChannelSelId = 'fcChannelSelId';
    
    public static String dtvClearId = 'dtvClearId';
    
    //CUSTOMER INFO AND APPROVAL PAGE
    public static String CustomerInfoPage = 'CustomerInfoPage';
    public static String ApprovalPage = 'ApprovalPage';
    
    //YOUBIO PAGE
    public static String YouBioPage = 'DealerYouBioProductSelection';
    public static String youBioId = 'youBioId';
}